services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
  app:
    image: wish-list-be
    depends_on:
      - db
    ports:
      - 13000:3001
