### 
GET http://localhost:3001/

###
POST http://localhost:3001/
Content-Type: application/json

{
    "name":"yaz",
    "company":"test"
}

####
POST http://localhost:3001/list
Content-Type: application/json

{
    "id": 3,
    "name":"test3",
    "description":"desc3",
    "allowReservation": true
}


### 
POST http://localhost:3001/item
Content-Type: application/json

{
    "id": 2,
    "name":"test3",
    "image":null,
    "link":null,
    "isReserved":"false",
    "listId":"3"
}
